 on: 

  workflow_dispatch:

env:
    # OrangeFox Sync Repository
    FOX_SYNC: https://gitlab.com/OrangeFox/sync.git

    # Config
    CONFIG: config.sh

    # Telegram
    
    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "Recovery Build"
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 8
      memory: 20G

  Checks_script:
      - bash -c "$(curl -sL https://github.com/Jayeudypdx/Orangefox-sm-x200/blob/main/scripts/checks.sh)"

  Sync_script:
      - bash -c "$(curl -sL https://github.com/Jayeudypdx/Orangefox-sm-x200/blob/main/scripts/sync.sh)"

  Build_script:
      - bash -c "$(curl -sL https://github.com/Jayeudypdx/Orangefox-sm-x200/blob/main/scripts/build.sh)"

  Upload_script:
      - export TIMEOUT=43200 # Link timeout (in minutes)
      - bash -c "$(curl -sL https://github.com/Jayeudypdx/Orangefox-sm-x200/blob/main/scripts/upload.sh)"
